### ISSUE TITLE
square/go-jose deprecated

### ISSUE THREAD

**Issue by yagehu** [clerkinc/clerk-sdk-go#105]
Calling out https://github.com/square/go-jose being deprecated and the official recommendation is to migrate to https://github.com/go-jose/go-jose.

**Comment by gkats** [comment]
Hi @yagehu, thanks for raising this! 

We're aware of the deprecation as we use the square/go-jose module in other projects as well.

We're currently evaluating alternatives and will update soon.

**Comment by yagehu** [comment]
Great. I want to get a sense of alternatives you are considering. We're using go-jose v3 everywhere else in our Go code.

**Comment by gkats** [comment]
@yagehu We ended up switching to go-jose/go-jose v3 as well in #108. It provides everything we need for our needs and it's a drop-in replacement so migration was easy.

We considered the following alternatives.
- https://github.com/golang-jwt/jwt
- https://github.com/kataras/jwt
- https://github.com/go-chi/jwtauth
- https://github.com/lestrrat-go/jwx

Of all the alternatives, lestrrat-go/jwx was the strongest contender. Eventually, since go-jose v3 does not have any breaking changes, we decided to stick with that.
